Algoritmo "ValoresABC"

Var
   a, b, c, soma: real


Inicio
      escreva ("Diíte o valor A: ")
      leia (a)
      escreva ("Digíte o valor B: ")
      leia (b)
      escreva ("Digíte o valor C: ")
      leia (C)
      soma <- a + b
      se (soma < c) entao
         escreva ("A soma dos Valores A e B resulta em um número Menor que o valor C")
      senao
           escreva ("A soma dos Valores A e B resulta em um número Maior que o valor C")

      FimSe
      

Fimalgoritmo