Algoritmo "NumerosIguais"

Var
   a, b, c: inteiro


Inicio
      escreva ("Digíte o valor A: ")
      leia (a)
      escreva ("Digíte o valor B: ")
      leia (b)
      se (a = b) então
         c <- a + b
           escreva ("O resultado da soma dos valores A e B resulta em:",c)
      senao
           c <- a * b
             escreva ("O resultado da multiplicação do valor A sobre B resulta em:", C)
             
      FimSe

Fimalgoritmo